### ISSUE TITLE
Scout demo database doesn't load Ancestry (pred.) or Parenthood

### ISSUE THREAD

**Issue by leahkemp** [Clinical-Genomics/scout#1989]
Hi all, thankyou for the great software!

I'm having loading some values into scout that should be included through these variables/files in the config file:

```yaml
peddy_ped: scout/demo/643594.peddy.ped
peddy_ped_check: scout/demo/643594.ped_check.csv
peddy_sex_check: scout/demo/643594.sex_check.csv
```

When the demo database is loaded, scout doesn't appear to be grabbing the values from these files to populate the Ancestry (pred.) and Parenthood columns of the 'Individuals' panel in the 643594 case (see images below):

![scout_parenthood_loading](https://user-images.githubusercontent.com/46519743/88131992-6699ad80-cc32-11ea-85dd-b4e8cb1c0ccf.PNG)
![scout_parenthood_loading_2](https://user-images.githubusercontent.com/46519743/88131995-67cada80-cc32-11ea-93c0-48037444dd22.PNG)

- No error messages are thrown when creating or serving the database.

- I'm using scout version 4.19 and python 3.7.6 installed within a conda environment.

Please let me know if you require any further details from me, thanks in advance for your help!
