### ISSUE TITLE
Update description of yaml config file in admin guide

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2330]
This file: http://www.clinicalgenomics.se/scout/admin-guide/load-config/

There are fields added recently that are not described

**Comment by mikaell** [comment]
I'll give it a shot.

I assume the attributes are somewhat sorted and grouped to functionality. I suggest using alphabetical order instead. For example:


```
  - analysis_type: wes
    capture_kit: Agilent_SureSelectCRE.V1
    chromograph_images:
        'autozygous': 'scout/demo/images/chromograph_demo/autozygous_regions'
        'coverage': 'scout/demo/images/chromograph_demo/coverage'
        'upd_regions': 'scout/demo/images/chromograph_demo/upd_regions'
        'upd_sites': 'scout/demo/images/chromograph_demo/upd_sites'
    expected_coverage: 30
    father: ADM1059A1
    mother: ADM1059A3
    mt_bam: scout/demo/reduced_mt.bam
    phenotype: affected
    sample_id: ADM1059A2
    sample_name: NA12882
    sex: male
    tissue_type: blood
    vcf2cytosure: scout/demo/ADM1059A2.dummy.cgh
```
