### ISSUE TITLE
Add custom images to scout case view

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2763]
We would like to populate the case view with custom images in svg format generated by our analysis pipelines. One solution would be to add an option for "custom panels" to be defined in `case.config.yaml` file. Perhaps a variant on the `chromograph_images` configuration.

For instance could the following section

```yaml
<section_name>_images:
 - title for image a:
   path: /path/to/image.svg
   description: a nice image
 - title for image b:
   path: /path/to/image.svg
   description: another nice image
```

generate something like this with the description as a tooltip

![image](https://user-images.githubusercontent.com/12696913/126658289-97c92412-de08-41d2-a9d2-a55e74098944.png)
