### ISSUE TITLE
 Improve LDAP authentication support

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2938]
Scouts support for LDAP authentication is fairly basic and the login documentation contains some minor errors.

It would be nice to describe how to use the authentication variables, LDAP_BIND_USER_DN  and LDAP_BIND_USER_PASSWORD and filtering variables LDAP_USER_DN and LDAP_GROUP_DN.

Also it would be good if we could mirror the function of `LDAP_REQUIRED_GROUP` so you could setup different user groups which has access to different softwares.

**Errors**
- Configuration variable `LDAP_REQUIRED_GROUP` is not supported by [flask-ldap3-login](https://flask-ldap3-login.readthedocs.io/en/0.9.16/configuration.html) flask-ldap3-login
- The documentation say that Scout supports login with username and password which is wrong. Scouts basic auth uses only email.

**Comment by mhkc** [comment]
I am currently using this openLDAP configuration to define the organization.

```
dn: ou=Employees,dc=cmd,dc=org
objectClass: organizationalUnit
ou: Employees

dn: ou=Groups,dc=cmd,dc=org
objectClass: organizationalUnit
ou: Groups

dn: cn=cdm-user,ou=Groups,dc=cmd,dc=org
objectClass: top
objectClass: posixGroup
cn: cdm-user
gidNumber: 5000

dn: cn=scout-user,ou=Groups,dc=cmd,dc=org
objectClass: top
objectClass: posixGroup
cn: scout-user
memberUid: viktor.henmyr@skane.se
memberUid: tord.jonson@skane.se
gidNumber: 5001

dn: cn=coyote-user,ou=Groups,dc=cmd,dc=org
objectClass: top
objectClass: posixGroup
cn: coyote-user
memberUid: viktor.henmyr@skane.se
gidNumber: 5002

dn: cn=cgwiz-user,ou=Groups,dc=cmd,dc=org
objectClass: top
objectClass: posixGroup
cn: cgwiz-user
gidNumber: 5003

## Scout users
dn: uid=markus.h.johansson@skane.se,ou=Employees,dc=cmd,dc=org
objectClass: inetOrgPerson
objectClass: shadowAccount
uid: markus.h.johansson@skane.se
sn: Johansson
givenName: Markus
cn: Markus Johansson
displayName: Markus Johansson
userPassword: laga

dn: uid=viktor.henmyr@skane.se,ou=Employees,dc=cmd,dc=org
objectClass: inetOrgPerson
objectClass: shadowAccount
uid: viktor.henmyr@skane.se
sn: Henmyr
givenName: Viktor
cn: Viktor Henmyr
displayName: Viktor Henmyr
userPassword: naga

dn: uid=tord.jonson@skane.se,ou=Employees,dc=cmd,dc=org
objectClass: inetOrgPerson
objectClass: shadowAccount
uid: tord.jonson@skane.se
sn: Jonson
givenName: Tord
cn: Tord Jonson
displayName: Tord Jonson
userPassword: maga
```

**Comment by northwestwitch** [comment]
I think I'll give it a try setting up a test LDAP server using the bitnami image: https://hub.docker.com/r/bitnami/openldap/

**Comment by mhkc** [comment]
I have a functional setup with [osixia/openldap](https://hub.docker.com/r/osixia/openldap) and using [wheelybird/ldap-user-manager](https://hub.docker.com/r/wheelybird/ldap-user-manager) to manage the database. It takes the configuration from a environment file which allows you to have separate environments and parameters for testing and production.

``` yaml
version: "3.9"
services:
  open-ldap:
    image: "osixia/openldap:${OPENLDAP_VERSION:-latest}"
    container_name: open-ldap
    volumes:
      - ./data/database:/var/lib/ldap
      - ./data/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=cmd
      - LDAP_DOMAIN=${ORGANISATION_NAME:-example}.${ORGANISATION_DOMAIN:-org}
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
    ports:
      - 389:389
    networks:
      - ldap-net
    restart: unless-stopped


  ldap-user-manager:
    image: "wheelybird/ldap-user-manager:${USER_MANAGER_VERSION:-oldcookies}"
    container_name: ldap-manager
    volumes:
      - ./mail_functions.inc.php:/opt/ldap_user_manager/includes/mail_functions.inc.php
    environment:
      - ORGANISATION_NAME=${ORGANISATION_NAME:-example}
      - SERVER_HOSTNAME=10.0.224.64:8090
      - LDAP_URI=open-ldap
      - LDAP_BASE_DN=dc=${ORGANISATION_NAME:-example},dc=${ORGANISATION_DOMAIN:-org}
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=${ORGANISATION_NAME:-example},dc=${ORGANISATION_DOMAIN:-org}
      - LDAP_ADMIN_BIND_PWD=${ADMIN_PASSWORD:-admin}
      - LDAP_IGNORE_CERT_ERRORS=true
      - USERNAME_FORMAT={first_name}.{last_name}
      # email settings
      - SMTP_HOSTNAME=${SMTP_HOSTNAME}
      - SMTP_HOST_PORT=${SMTP_HOST_PORT}
      - SMTP_USE_TLS=false
      - SMTP_USE_SSL=false
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS:-noreply@$LDAP_DOMAIN}
      - EMAIL_DOMAIN=${ORGANISATION_NAME:-example}.${ORGANISATION_DOMAIN:-org}
      - EMAIL_FROM_NAME=CMD
      - ACCOUNT_REQUESTS_ENABLED=true
      - ACCOUNT_REQUESTS_EMAIL=${ACCOUNT_REQUESTS_EMAIL}
      - NEW_ACCOUNT_EMAIL_BODY=${NEW_ACCOUNT_EMAIL_BODY}
      - NEW_ACCOUNT_EMAIL_SUBJECT=${NEW_ACCOUNT_EMAIL_SUBJECT}
      # General
      - NO_HTTPS=true
      - SMTP_LOG_LEVEL=1
    expose:
      - '25'
    ports:
      - 8090:80
    networks:
      - ldap-net
    restart: unless-stopped

networks:
  ldap-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
```
