### ISSUE TITLE
Rename Custom Image Parameters "case" and "str"

### ISSUE THREAD

**Issue by mikaell** [Clinical-Genomics/scout#3084]
In the configuration file it is since a few version back possible to configure custom images. But the parameters "str" and "case" are named poorly and should be renamed.

```
custom_images:
  str:
    - title: A png image
    [...]
  case:
    section_one:
    [...]
```

Why?
* Python has a built in function `str()`
* The parameters are too short and non-descriptive
* `case` is not reserved, but commonly used in a case-statement. But also too short and non-descriptive
