### ISSUE TITLE
Report versions of MIP, callers & references 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#442]
It would be prudent in general to allow access to the version report for a case through scout. If nothing else, versions of MIP, crucial references such as ExAC, OMIM, genome, gene models (i e transcript set) and aligners/callers would be expected. This would probably fit well in the discussion of displaying deltas to reruns in #381.

**Comment by robinandeer** [comment]
as far as this is reported in MIP we will try to incorporate this information!

**Comment by robinandeer** [comment]
perhaps it's even included in the VCF if we are lucky... :P

**Comment by moonso** [comment]
Maybe @henrikstranneheim could add that otherwise?

**Comment by henrikstranneheim** [comment]
Most of it is in qc_metrics or sample_info or the mip_logg. We need to put together a list of things that we want to see and then I can add them as appropriate (but most probably not the vcf file header unless the program responsible already added it there)

**Comment by dnil** [comment]
The load config yaml is fine. How about we start with MIP version, plus, if any, references/programs that we allow ourselves to update independently. The bulk of actual component software versions, references versions etc could then be listed in static files, much like the rank models?

**Comment by moonso** [comment]
So weird that this one is still open... and that it has made it all the way to legendary status 🤣 
Should we just complete it?

**Comment by dnil** [comment]
Well, you have assigned at some point... 😉

**Comment by henrikstranneheim** [comment]
Mip currently produces these files:
```
cat develop/livingox/analysis/reference_info.yaml
---
cadd_vcf_header_file: /home/henrik.stranneheim/develop/mip_references/cadd_to_vcf_header_-1.0-.txt
chromograph_cytoband_file: /home/henrik.stranneheim/develop/mip_references/grch37_cytoband.bed
delly_exclude_file: hg19_human_excl_-20150227-.tsv
exome_target_bed:
  /home/henrik.stranneheim/develop/mip_references/grch37_agilent_sureselect_targets_cre_-v1-.bed: 'ACC5339A4,ACC5339A2,ACC5339A3'
expansionhunter_variant_catalog_file_path: /home/henrik.stranneheim/develop/mip_references/grch37_expansionhunter_variant_catalog_-3.1.2-.json
fqa_vcfanno_config: /home/henrik.stranneheim/develop/mip_references/grch37_frequency_vcfanno_filter_config_-v1.3-.toml
gatk_baserecalibration_known_sites:
  - /home/henrik.stranneheim/develop/mip_references/grch37_dbsnp_-138-.vcf
  - /home/henrik.stranneheim/develop/mip_references/grch37_1000g_indels_-phase1-.vcf
  - /home/henrik.stranneheim/develop/mip_references/grch37_mills_and_1000g_-gold_standard_indels-.vcf
gatk_calculate_genotype_call_set: /home/henrik.stranneheim/develop/mip_references/grch37_gnomad.genomes_-r2.0.1-.vcf.gz
gatk_genotypegvcfs_ref_gvcf: /home/henrik.stranneheim/develop/mip_references/grch37_gatk_merged_reference_samples.txt
gatk_haplotypecaller_snp_known_set: /home/henrik.stranneheim/develop/mip_references/grch37_dbsnp_-138-.vcf
gatk_varianteval_dbsnp: /home/henrik.stranneheim/develop/mip_references/grch37_dbsnp_-138_esa_129-.vcf
gatk_varianteval_gold: /home/henrik.stranneheim/develop/mip_references/grch37_mills_and_1000g_-gold_standard_indels-.vcf
gatk_variantrecalibration_resource_indel:
  /home/henrik.stranneheim/develop/mip_references/grch37_dbsnp_-138-.vcf: 'dbsnp,known=true,training=false,truth=false,prior=2.0'
  /home/henrik.stranneheim/develop/mip_references/grch37_mills_and_1000g_-gold_standard_indels-.vcf: 'mills,known=false,training=true,truth=true,prior=12.0'
gatk_variantrecalibration_resource_snv:
  /home/henrik.stranneheim/develop/mip_references/grch37_1000g_omni_-2.5-.vcf: 'omni,known=false,training=true,truth=truth,prior=12.0'
  /home/henrik.stranneheim/develop/mip_references/grch37_1000g_snps_high_confidence_-phase1-.vcf: '1000G,known=false,training=true,truth=false,prior=10.0'
  /home/henrik.stranneheim/develop/mip_references/grch37_dbsnp_-138-.vcf: 'dbsnp,known=true,training=false,truth=false,prior=2.0'
  /home/henrik.stranneheim/develop/mip_references/grch37_hapmap_-3.3-.vcf: 'hapmap,known=false,training=true,truth=true,prior=15.0'
genmod_annotate_cadd_files:
  - /home/henrik.stranneheim/develop/mip_references/grch37_cadd_whole_genome_snvs_-v1.4-.tsv.gz
  - /home/henrik.stranneheim/develop/mip_references/grch37_cadd_gnomad.genomes.r2.0.1_-v1.4-.tsv.gz
genmod_annotate_spidex_file: /home/henrik.stranneheim/develop/mip_references/grch37_spidex_public_noncommercial_-v1_0-.tab.gz
genmod_models_reduced_penetrance_file: /home/henrik.stranneheim/develop/mip_references/grch37_cust003-cmms-red-pen_-2017-.tsv
human_genome_reference: /home/henrik.stranneheim/develop/mip_references/grch37_homo_sapiens_-d5-.fasta
nist_call_set_bed:
  '2.19':
    NA12878: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg001_-na12878_v2.19-.bed
  3.3.2:
    NA12878: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg001_-na12878_v3.3.2-.bed
    NA24143: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg004_-na24143_v3.3.2-.bed
    NA24385: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg002_-na24385_v3.3.2-.bed
nist_call_set_vcf:
  '2.19':
    NA12878: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg001_-na12878_v2.19-.vcf
  3.3.2:
    NA12878: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg001_-na12878_v3.3.2-.vcf
    NA24143: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg004_-na24143_v3.3.2-.vcf
    NA24385: /home/henrik.stranneheim/develop/mip_references/grch37_nist_hg002_-na24385_v3.3.2-.vcf
qccollect_regexp_file: /home/henrik.stranneheim/develop/mip_references/qc_regexp_-v1.24-.yaml
rank_model_file: /home/henrik.stranneheim/develop/mip_references/rank_model_cmms_-v1.28-.ini
rhocall_frequency_file: /home/henrik.stranneheim/develop/mip_references/grch37_gnomad.genomes_-r2.0.1-.tab.gz
rtg_vcfeval_reference_genome: /home/henrik.stranneheim/develop/mip_references/grch37_homo_sapiens_-d5-.fasta
sv_fqa_vcfanno_config: /home/henrik.stranneheim/develop/mip_references/grch37_sv_frequency_vcfanno_filter_config_-v1.2-.toml
sv_genmod_models_reduced_penetrance_file: /home/henrik.stranneheim/develop/mip_references/grch37_cust003-cmms-red-pen_-2017-.tsv
sv_rank_model_file: /home/henrik.stranneheim/develop/mip_references/svrank_model_cmms_-v1.8-.ini
sv_svdb_query_db_files:
  /home/henrik.stranneheim/develop/mip_references/grch37_gnomad.genomes_-r2.1.1_sv-.vcf: gnomad_sv|AF|AC|AF|AC|1
  /home/henrik.stranneheim/develop/mip_references/grch37_mip_sv_svdb_export_-2018-10-09-.vcf: clinical_genomics_mip|AF|OCC|FRQ|OCC|1
  /home/henrik.stranneheim/develop/mip_references/grch37_svdb_query_clingen_cgh_benign_-v1.0.0-.vcf: clingen_cgh_benign
  /home/henrik.stranneheim/develop/mip_references/grch37_svdb_query_clingen_cgh_pathogenic_-v1.0.0-.vcf: clingen_cgh_pathogenic
  /home/henrik.stranneheim/develop/mip_references/grch37_svdb_query_clingen_ngi_-v1.0.0-.vcf: clingen_ngi|AF|OCC|FRQ|OCC|1
  /home/henrik.stranneheim/develop/mip_references/grch37_svdb_query_decipher_-v1.0.0-.vcf: decipher|AF|OCC|FRQ|OCC
  /home/henrik.stranneheim/develop/mip_references/grch37_swegen_concat_sort_-20170830-.vcf: swegen|AF|OCC|FRQ|OCC|1
vcf2cytosure_blacklist: /home/henrik.stranneheim/develop/mip_references/grch37_cytosure_blacklist_-1.0-.bed
vep_custom_annotation:
  clinvar:
    annotation_type: exact
    file_type: vcf
    force_report_coordinates: '0'
    key: CLINVAR
    path: /home/henrik.stranneheim/develop/mip_references/grch37_clinvar_reformated_-20191013-.vcf.gz
    vcf_fields: 'CLNSIG,CLNVID,CLNREVSTAT'
  genomic_superdups_frac_match:
    annotation_type: overlap
    file_type: bed
    force_report_coordinates: '0'
    key: genomic_superdups_frac_match
    path: /home/henrik.stranneheim/develop/mip_references/grch37_genomics_super_dups_-20181009.bed.gz
vep_directory_cache: /home/henrik.stranneheim/develop/mip_references/ensembl-tools-release-97/cache
vep_plugin:
  ExACpLI:
    exists_check: file
    path: /home/henrik.stranneheim/develop/mip_references/gnomad_pli_per_gene_-_r2.1.1-.txt
  LoFtool:
    exists_check: file
    path: /home/henrik.stranneheim/develop/mip_references/ensembl-tools-release-97/cache/Plugins/LoFtool_scores.txt
  MaxEntScan:
    exists_check: directory
    parameters:
      - SWA
      - NCSS
    path: /home/henrik.stranneheim/develop/mip_references/ensembl-tools-release-97/cache/Plugins/fordownload
  dbNSFP:
    exists_check: file
    parameters:
      - GERP++_RS
      - GERP++_NR
      - phyloP100way_vertebrate
      - phastCons100way_vertebrate
      - REVEL_rankscore
    path: /home/henrik.stranneheim/develop/mip_references/grch37_dbnsfp_-v3.5a-.txt.gz
vep_plugins_dir_path: /home/henrik.stranneheim/develop/mip_references/ensembl-tools-release-97/cache/Plugins
```

and software versions:
```
cat /home/proj/production/housekeeper-bundles/maindrum/2020-03-06/maindrum_vcol.yaml
---
ExpansionHunter: v3.1.2
TIDDIT.py: 2.8.0
bcftools: 1.9 (using htslib 1.9)
bedtools: v2.29.0
bgzip: '1.9'
bwa: 0.7.17-r1188
chanjo: 4.2.0
configManta.py: 1.6.0
fastqc: v0.11.8
gatk: v4.1.3.0
genmod: 3.7.3
grep: '2.20'
gzip: '1.5'
multiqc: '1.7'
peddy: 0.4.3
picard: ~
plink2: v1.90p 64-bit (25 Mar 2016)
rhocall: 0.5.1
sambamba: 0.6.8
samtools: 1.9 (using htslib 1.9)
sed: 4.2.2
stranger: 0.5.5
svdb: '2.2.0,'
tabix: '1.9'
variant_integrity: 0.0.4
vcf2cytosure: ~
vcfanno: 0.3.2
vep: '97'
vt: v0.5
```
I guess I can easily add mip own version to that as well.

Regarding VEP data, this is parsed in qc_metrics, but I think it would be better if Scout picked it up from the actual VCF header:
`##VEP="v97" time="2020-03-08 07:00:26" cache="/home/proj/production/rare-disease/references/references_8.0/ensembl-tools-release-97/cache/homo_sapiens_merged/97_GRCh37" ensembl-io=97.dc917e1 ensembl=97.378db18 ensembl-variation=97.26a059c ensembl-funcgen=97.24f4d3c 1000genomes="phase3" COSMIC="86" ClinVar="201810" ESP="20141103" HGMD-PUBLIC="20174" assembly="GRCh37.p13" dbSNP="151" gencode="GENCODE 19" genebuild="2011-04" gnomAD="r2.1" polyphen="2.2.2" refseq="01_2015" regbuild="1.0" sift="sift5.2.2"
`
But I wonder if they (VEP) forgot to update the entries in there that VEP outputs. They look rather old. However, you can see from the MIP reference file that we are using a newer version of clinvar, but with the next release we should update it again.

I think we should sit down together and discuss what we want and in what format and from where.
