### ISSUE TITLE
Parse new format for pipeline info?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4523]
nf-core raredisease, tomte and probably rna-fusion have a new structure for pipeline info (yml):
```
BCFTOOLS_INDEX:
  bcftools: 1.18
BCFTOOLS_MPILEUP:
  bcftools: 1.18
BCFTOOLS_VIEW:
  bcftools: 1.18
BOOTSTRAPANN:
  python: 3.9.10
CAT_FASTQ:
  cat: 8.3
DROP_CONFIG_RUN_AE:
  drop_config: null
  drop: v1.3.3
DROP_CONFIG_RUN_AS:
  drop_config: null
  drop: v1.3.3
DROP_FILTER_RESULTS:
  drop_filter_results: null
```
I think we probably only pdf-convert them right now, but lets check so that they are fine.
