### ISSUE TITLE
No reads shown for MT variants in internal IGV

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4866]
**Describe the bug**

Previously (before updating 4.81 -> 4.88), when navigating to an MT variant page, it was possible to bring up the IGV viewer track including coverage tracks.

Now coverage tracks are only present for non MT variants.

A working variant:

![igv_working](https://github.com/user-attachments/assets/ca7836d4-753b-4604-93f1-317ba1e5b2fa)

A non working MT-variant:

![igv_m_not_working](https://github.com/user-attachments/assets/5eed96b9-4d11-40fb-bdef-fa31d9b15c9f)

Accessed from this "IGV viewer" button:

![case_view](https://github.com/user-attachments/assets/7009ef5c-c6ee-4ce9-af94-fa6ee4f1b6e5)

**Additional info**

I saw the IGV JS was updated in 4.88.1, so I tried running on that version. Same situation there - no MT tracks in neither 4.88 nor 4.88.1

A recurrent issue is that we here in Lund call the mitochondrial chromosome "M" instead of "MT". Might it be something related to that?

**Comment by northwestwitch** [comment]
Hi @Jakob37, where are your MT variants read from, same alignment file as the other variants or are they on a separate file (bam/cram) ?

**Comment by dnil** [comment]
Right, always interesting with reference genomes. It looks like you are getting the IGV view and the correct locus, but the alignment is not showing. Is that correct?

**Comment by Jakob37** [comment]
> Hi @Jakob37, where are your MT variants read from, same alignment file as the other variants or are they on a separate file (bam/cram) ?

They are stored in a separate bam file, here is how a sample can look in the case yaml:

```
---
owner:
family: 'hg002'
lims_id: '0000-00'
samples:
  - analysis_type: wgs
    sample_id: 'hg002'
    sample_name: 'hg002'
    mother: '0'
    father: '0'
    capture_kit:
    phenotype: affected
    sex: male
    bam_path: /access/wgs/bam/hg002_dedup.bam
    mt_bam: /access/wgs/bam/hg002_mito.bam
    d4_file: /access/wgs/cov/hg002_coverage.d4
```

> Right, always interesting with reference genomes. It looks like you are getting the IGV view and the correct locus, but the alignment is not showing. Is that correct?

Yes, that is how I understand it!
