### ISSUE TITLE
Add sv rank model version to case page

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#493]

**Comment by henrikstranneheim** [comment]
![screen shot 2018-01-16 at 13 33 23](https://user-images.githubusercontent.com/584738/34989242-1bb90c28-fac2-11e7-95f0-2431bcacffc4.png)

**Comment by patrikgrenfeldt** [comment]
"Hej,

MIP heter “tagen” på filen: “sv_rank_model”

Mvh
Henrik Stranneheim"

**Comment by moonso** [comment]
What?

**Comment by dnil** [comment]
@henrikstranneheim: Is this available only in MIP v7 or also MIP v6? If the latter we can issue / PR CG  as well.

**Comment by henrikstranneheim** [comment]
It is available in MIP v6 from the [case_id]_qc_sample_info.yaml file:
```
   sv_rank_model:
      file: svrank_model_cmms_-v1.3-.ini
      path: [path_to]/svrank_model_cmms_-v1.3-.ini
      version: '1.3'
```
I guess it have to be supplied by cg to the Scout config, in the same way as the snv/indel rank model.
