### ISSUE TITLE
How to provide bam-files for scout

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#726]
When viewing a variant in a case I've loaded, scout tells me that no bam file was provided. I've looked around, but the example config files do not seem to show what the keyword should be for providing a bam file with a case.

Can you share how to add bam files to a case?

**Comment by moonso** [comment]
Sry about that, it should be added to the documentation.
In the load config you add a key for each individual called `'bam_file': str`.
So in to take the demo file as an example it would look like:

```yaml
---

owner: cust000

family: '643594'
family_name: '643594'
samples:
  - analysis_type: wes
    sample_id: ADM1059A2
    capture_kit: Agilent_SureSelectCRE.V1
    father: ADM1059A1
    mother: ADM1059A3
    sample_name: NA12882
    phenotype: affected
    sex: male
    expected_coverage: 30
  - analysis_type: wes
    sample_id: ADM1059A1
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12877
    phenotype: unaffected
    sex: male
    expected_coverage: 30
    bam_file: path/to/bam
```
