### ISSUE TITLE
Bam-file not loaded

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#753]
When looking at variants, Scout displays "Bam file(s) missing," even though I've added the bam-file to the case (and no messages are related to this in the logs).

The first part of the case file looks like this:

```
---

owner: bonkolab

family: '57PGF'
family_name: '57PGF'
samples:
  - analysis_type: wes
    sample_id: 57PGF
    capture_kit: BGI
    father: 0
    mother: 0
    sample_name: 57
    phenotype: affected
    sex: male
    expected_coverage: 30
    bam_file: /home/projects/.../bam_filename.bam
```

What can I do to debug?

Thanks.
